language: go
go:
  - '1.10'
env:
  global:
    - secure: >-
        XSSU38Wy3ZHxO1FtwlfjGMqB9D2R29a42qCHfH2sVyT6gcLQhQFeRiK60g/InNX1SQs95xNcF+j9i2o4Cq71+1erhFQjhA8rUh5f2TgvtFLniEZ2uHg4EO9SENBy74Y1oz7P/jn/zRcHpnorA0V/3jRmUa0TLMiWlB3QKx4mNosUG5N0bnBLoZlZG0KdRt4y7sqM6X3zALrK/fgNcXZkBWVKaVYCkhS6k0kxrGLyEDdZaFkSUOcg/XCKjQXTT3IGqS/CNceqBaa7Tbn9OSdb617TocFMyoMw2JLw5E8gAMSjIQz0TsdsUTppzDzdcRiHwm3/AkwR1gY0lO51Qn7vyngmVyEunsCep02HFPu70sxDL2EWCQI0QcmP4nxg4eUzjFLWpxyEePjBhmNLjrHlO/MF0FUkeeAYoP7X12PqmobNcoER0fsxpUWIL2NvzNbM8ieK76mxmQ146tyAAA7xJJXDiUAf+pV/oVP0iy4Csx9d3zm2cTZPjhdLRVCCp3JjUUh8Mf0LKbhS3DR5CPt4VOd7FAQRIAmZ+xn8CN8brwX52ZSF/KRnBzvl/31SD41qQVEOInHH4dbaoRiVqZmfKPr36qjwpMq07cRNUfLOHjIVG7MzQbZPtqIXAdM8wV8BjFXiYVwYBhdHoRCm6fN9BPDe5K7FvQwV6KhAc4ZKW9s=
