language: go
go:
  - "1.10"

env:
  global:
    secure: wQzbbtxbm27RlxuTr3FBuDsvXytmPT0bhYVaF6wzAn783/JVKI3XWdGhvXBL2KTcC0g1x5UrYvFDBIeAX5DjIXgVBxFFtRU878fHJZU762asvWh4HYzkKcMvpsCB+adJJGsRszC2J3r21B89aHuVkRv2Yx734wDDCjqERqwhsTr7qR4IKmh7Z7bf9ln4nRG6nCc2FD5udE+5B6cmXvcc7MO7+ZFSkNmhgeUVkzS5C5Kf2d6nNFTwr16ik5Axb2v79bQFQBt/rzICyZcO/UKu3NxuA+18RxOTFemFTX/yf3HuLKlUFW/+1tpj3jbCKafg+eHx9rp4fs+8y+1HgtRLROBvgMps8oS10vgXRpeM5C1S98QT+PPN4nGRP4Wf3l/mftOtvHc/9+987AZMeIxl7CBlD06Iq84dLqeiXSaWSQnJVNUyKQHKgA+f68fjXOf4btnLvK6jI3vPKR9/QY+KvxJaCddNQ1qZ4cDuenDEDjz0y1CIaxpAybToGEXaOQxMgz3ynOlGddkKo3btFB2LKSXRQdGgzUoHOggxf0shl40fJN+Ng+YAN4Hxh51G+otuTpqqYZSERcPVXEKSkNT2l0NFeSZSgWcE/71jGCTYGMrrSC3LV1QUFV30MN4tut0X8IpD73+W8rwDS+/uyqDdJt8SjkWFKeer4iBI0VRJdsM=
