language: go
go:
  - "1.10"

env:
  global:
    secure: 0qB+8eEuZpkcuG7ZwH7dUusVGNtj+Oh7D0JC4pQF5AnzpiJwwinHxploAncyxCn3A05AQtAPIuxbs1NB88Gu2TzCnNuSpjev0PDyhFiUMZQ/mRtJVJCRKtt564vAI76Eo6UaOTVi2mOr3EFoAdepjaw9bFyUEdixVGWZWCTfTOg/7JwnW2nDw3Va3i+ymZQcLPamfsSO/oLLGq+vnxljNedQArkTZVCQIAzYAZMsmrKEdoj0PQDDHAc5GMmXjwwARsaGgITMRjgsyru3dmEoyO3A2EbXV4cd6BYWj3gdI07HNm2aAO8w5B68JwukOp4jB5mR50ASAmCS0a3qJ8m1xsfWE4rV4miGBjTDg4c9p4mF2ahmAl59sDtNbC1+Iq8bQZTRd/sz1QARnczbHDYpffQTaB84MkMDDyhSUwh7RE6/7US4YNJ59jhDfWH/y11fRudQvSgLuM8SIladwSXS+VMFN63a0i5nSPZbXlDr5+VXqI/LunAIwo9yuhRztHqb3/sCoeRKiEBQNXOHdffnmw4K7DZX2u9x+D16nB20RulW+ipNZ/JSqZmin2zCsi0bHVJAY1RqJH2CAEzWBnICNv2Y9xfVpZL3vaFNdVkCeRlK6u2c1o7a6GrPMbdeO1PH4xulHe4PRlSnc+UZyBf/JVr8VkOzSoLhIA1k9KG5WW0=
