language: go
go:
  - '1.10'
env:
  global:
    - secure: >-
        TF/ZtwkGyPKQMny3Eo/Sd5D9D4AMN+xonOZz7nbHUi7M55UqXuzrntiWTfQnjBZqKh0uNOdgRmfYEWnbv0nNqdPSNFd0nuY8ktGMXJYcLWIdoCO3dWu033lkmG4K+79fZl7NE3/q9yACS5/PhWLDiYJmmDCpExKcRrS3Hr13svJiGLoNbd8QIG4aP/DaHReuhlz++nlhHQpzKxINjGaBGcQwR9//exH8tnmz3taqeBBJALuz3tv1RC7scNBDw3mWeZWLPB4e4lRqM2jh73mD4uwh1xDkvKshwN3CxfmlX4yvJx+MbfgrYy+Tra5f5JrgO59EY61/7e2oor/qTupudElXowfRx1HGGU7ywK//adzLqe6Rsmv4D3SEJz8Fw+8nGt9sV5Pz6EXwXd31ojf5UrY8Wg1bKXaRQf2UfGm4J4FzlxPUGBfMvjat6ZNMcMJYR1cM3G/PrpDc1pkKmUxo3taGe/T1/xBmqSRBZaWxA9dZ5/CmvHi3WjoOSwdfT5q7ZbgAIW//87GrCJ4zFnO/U2pyaA+iXPECyCnHVXfG1UulVeDpNQHZgP/gM3BAlORNmjG3GRya7QWhnn/HSWxkindPvP7ZWQZ/NWBC41PW3JKdly/JXuwoPE9THs+5dTxtatjRc5K5RgVQFmv12pL+SVNgJ3159Qf+BEvY1lIw+kM=
